Correctif des dégats a la mascotte pendant la guerre (#961)
* add: lore price for skin

* fix: mascots damage

* fix: mascots damage (2)

* fix: Could not pass event CooldownEndEvent to OpenMC v2.0.0-beta-27-hotfix
     java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.setGlowing(boolean)" because "entityMascot" is nul